### PR TITLE
Flutter sdk & packages upgraded to the last versions.

### PR DESCRIPTION
**Pull request by E-MRE**
Flutter version & network info plus package version upgraded.

### CODE REVIEW

**Comment by abdu292** [comment]
@diantahoc @E-MRE Thanks a bunch for both of your great work & help on this. 
@diantahoc It'd be great if we can merge this PR & push a new release. This works even with the latest version released yesterday at Google IO 2024.

Until this is merged, I'm using the below (hope this helps someone):
```
  flutter_pos_printer_platform_image_3:
    git:
        url: https://github.com/diantahoc/flutter_pos_printer_platform.git
        ref: 9624e1cea4a4bf669ca31f5ff7f45b251581a512
```

**Comment by maurovanetti** [comment]
Hello.
Trying to use this fix, the build failed on Codemagic in the generation step:

```
> flutter.BAT build windows --release

windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
Building Windows application...                                 
CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:flutter_pos_printer_platform_image_3_plugin>

  No target "flutter_pos_printer_platform_image_3_plugin"


CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:flutter_pos_printer_platform_image_3_plugin>

  No target "flutter_pos_printer_platform_image_3_plugin"


CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:flutter_pos_printer_platform_image_3_plugin>

  No target "flutter_pos_printer_platform_image_3_plugin"
```

@E-MRE can you explain what we're doing wrong?

**Comment by maurovanetti** [comment]
I've solved my problem by renaming my fork of `flutter_pos_printer_platform_image_3` to `flutter_pos_printer_platform` again.
Apparently, for some reason the `_image_3` bit breaks the Windows build.

You can check our fix (or workaround?) here: https://github.com/in4matic-srl/flutter_pos_printer_platform/tree/renamed

The cascade forking is going out of control, so I don't know if I should submit a PR and where.

**Review by Skyloft15 — APPROVED** [review]

**Review by Skyloft15 — APPROVED** [review]

**Comment by ivankasalo** [comment]
Getting problems when upgrading  my android project to target targetSdkVersion of 34. For some reason bluetoothService is not being initialized. Problem is happening literary on permission requests. 
@E-MRE @diantahoc this is kind of urgent because of google play target policy described in https://support.google.com/googleplay/android-developer/answer/11926878

**Comment by okunadeola** [comment]
Also getting similar initialization issue specifically with the bluetooth and usb service. below is the thrown issue 

E/MethodChannel#com.sersoluciones.flutter_pos_printer_platform( 6189): Failed to handle method call
E/MethodChannel#com.sersoluciones.flutter_pos_printer_platform( 6189): kotlin.UninitializedPropertyAccessException: **lateinit property bluetoothService has not been initialized**
E/MethodChannel#com.sersoluciones.flutter_pos_printer_platform( 6189): 	at com.sersoluciones.flutter_pos_printer_platform.FlutterPosPrinterPlatformPlugin.verifyIsBluetoothIsOn(FlutterPosPrinterPlatformPlugin.kt:307)
E/MethodChannel#com.sersoluciones.flutter_pos_printer_platform( 6189): 	at com.sersoluciones.flutter_pos_printer_platform.FlutterPosPrinterPlatformPlugin.onMethodCall(FlutterPosPrinterPlatformPlugin.kt:221)
E/MethodChannel#com.sersoluciones.flutter_pos_printer_platform( 6189): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)

**Comment by harshchovatiya15** [comment]
> Getting problems when upgrading my android project to target targetSdkVersion of 34. For some reason bluetoothService is not being initialized. Problem is happening literary on permission requests. @E-MRE @diantahoc this is kind of urgent because of google play target policy described in https://support.google.com/googleplay/android-developer/answer/11926878

It is not working after update targetSdkVersion from 33 to 34, So please give solution for this

**Comment by ivankasalo** [comment]
> > Getting problems when upgrading my android project to target targetSdkVersion of 34. For some reason bluetoothService is not being initialized. Problem is happening literary on permission requests. @E-MRE @diantahoc this is kind of urgent because of google play target policy described in https://support.google.com/googleplay/android-developer/answer/11926878
> 
> It is not working after update targetSdkVersion from 33 to 34, So please give solution for this

I tried some things, like update agp, and other stuff to at least to match requirement but problem still occurs. From the documentation of the FlutterPlugin package I have no clue what could be the problem, they do not mansion anything about changes when targeting api level 34. Maybe I will try to experiment on a new plugin to see what is happening but as for now this package is not working.

**Comment by diantahoc** [comment]
> Getting problems when upgrading my android project to target targetSdkVersion of 34. For some reason bluetoothService is not being initialized. Problem is happening literary on permission requests. @E-MRE @diantahoc this is kind of urgent because of google play target policy described in https://support.google.com/googleplay/android-developer/answer/11926878

Hello, the problem is now fixed as of version 1.2.4

**Pull request merged**
